version: '3'

services:
  db:
    image: mysql:8.0
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "gymbro_db"
      MYSQL_USER: "erp_user"
      MYSQL_PASSWORD: "erp_password"
    volumes:
      - ./gymbro:/docker-entrypoint-initdb.d
    container_name: gymbro_db