name: Docker build and push to Artifact Registry

on:
  push:
    branches:
      - main
      - github-action

env:
  PROJECT_ID: pragmatic-zoo-425418-a3
  GAR_LOCATION: us-east4
  REPOSITORY: infocode1901
  IMAGE: api-auth

jobs:
  login-build-push:
    name: Docker login, build, and push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: Get latest tag
        id: latest_tag
        run: |
          VERSION_PREFIX="v"
          LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "$VERSION_PREFIX0.0.0")
          if [ "$LATEST_TAG" = "$VERSION_PREFIX0.0.0" ]; then
            echo "No valid tag found. Latest tag: $LATEST_TAG"
            exit 1
          fi
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v0.6.0
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Docker login
        uses: docker/login-action@v1
        with:
          registry: '${{ env.GAR_LOCATION }}-docker.pkg.dev'
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.access_token }}'

      - name: Docker build
        run: |
          docker build \
            --tag "$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:${{ env.LATEST_TAG }}"

      - name: Docker push
        run: |
          docker push "$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:${{ env.LATEST_TAG }}"
